/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  greenidOverview: [
    {
      type: "autogenerated",
      dirName: "greenid-overview"
    },
  ],
  developerGuides: [
    {
      type: "autogenerated",
      dirName: "developer-guides"
    },
  ],
  integrationMethods: [
    {
      type: "autogenerated",
      dirName: "integration-methods"
    },
  ],
  // not needed as Redocusaurus generates the side bar
  // apiReference: [
  //   {
  //     type: "autogenerated",
  //     dirName: "api-reference"
  //   },
  // ],
  updatesAndRelease: [
    {
      type: "autogenerated",
      dirName: "updates-and-releases"
    },
  ],
  customerSupportFaqs: [
    {
      type: "autogenerated",
      dirName: "customer-support-faqs"
    },
    {
      type: "link",
      label: "greenID (GBG) Status Page",
      href: "https://www.gbgstatus.com/",
    }
  ],
};

export default sidebars;
